---
# tasks file for grub
- name: local config
  template:
    src: local.cfg.j2
    dest: /etc/default/grub.d/local.cfg
    owner: root
    group: root
    mode: 0644
  when:
    grub_config is defined
  notify: update-grub
  tags:
    - grub
    - default
